/**
 * Run with: npm run seed
 * Requires NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local
 */
import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const categories = [
  { slug: "cleansers", name_en: "Cleansers", name_ko: "클렌저", name_uz: "Tozalagichlar", name_ru: "Очищение", sort_order: 1, description_en: "The first step of every ritual.", description_uz: "Har bir ritualning birinchi qadami.", description_ru: "Первый шаг любого ритуала." },
  { slug: "serums", name_en: "Serums", name_ko: "세럼", name_uz: "Serumlar", name_ru: "Сыворотки", sort_order: 2, description_en: "Concentrated actives for targeted results.", description_uz: "Maqsadli natijalar uchun konsentrlangan faol moddalar.", description_ru: "Концентрированные активы для целевых результатов." },
  { slug: "moisturizers", name_en: "Moisturizers", name_ko: "모이스처라이저", name_uz: "Namlagichlar", name_ru: "Увлажнение", sort_order: 3, description_en: "Lock in hydration, seal the ritual.", description_uz: "Namlikni saqlab, ritualni yakunlang.", description_ru: "Закрепите увлажнение, завершите ритуал." },
  { slug: "sunscreens", name_en: "Sunscreens", name_ko: "선크림", name_uz: "Quyoshdan himoya", name_ru: "Санскрин", sort_order: 4, description_en: "Non-negotiable, every single morning.", description_uz: "Har kuni ertalab majburiy himoya.", description_ru: "Обязательно каждое утро." },
  { slug: "makeup", name_en: "Makeup", name_ko: "메이크업", name_uz: "Makiyaj", name_ru: "Макияж", sort_order: 5, description_en: "Skin-first color, Korean technique.", description_uz: "Teri birinchi rang, koreys texnikasi.", description_ru: "Цвет, ориентированный на кожу, корейская техника." },
  { slug: "body-care", name_en: "Body Care", name_ko: "바디케어", name_uz: "Tana parvarishi", name_ru: "Уход за телом", sort_order: 6, description_en: "The ritual, from neck to toe.", description_uz: "Ritual, bo'yindan oyoqgacha.", description_ru: "Ритуал от шеи до пальцев ног." },
];

const products = [
  // ========== ANUA ==========
  {
    slug: "anua-heartleaf-77-toner",
    brand: "Anua",
    name_en: "Heartleaf 77% Soothing Toner",
    name_uz: "Heartleaf 77% tinchlantiruvchi toner",
    name_ru: "Heartleaf 77% успокаивающий тонер",
    name_ko: "하트립 77% 수딩 토너",
    description_en: "Cult-favorite toner with 77% Heartleaf extract. Calms irritation, reduces redness, and prepares skin for the rest of your routine. Alcohol-free and gentle enough for sensitive skin.",
    description_uz: "77% Heartleaf ekstrakti bilan mashhur toner. Tirnashishni tinchlantiradi, qizarishni kamaytiradi va terini keyingi bosqichlarga tayyorlaydi.",
    description_ru: "Культовый тонер с 77% экстракта Хартлиф. Успокаивает раздражение, уменьшает покраснение и готовит кожу к дальнейшему уходу.",
    category_slug: "serums",
    price_usd: 22,
    compare_at_price_usd: 28,
    sku: "ANUA-TON-001",
    stock: 85,
    ingredients: "Houttuynia Cordata Extract 77%, Panthenol, Hyaluronic Acid, Allantoin",
    benefits: "Soothes irritation, reduces redness, hydrates, strengthens barrier.",
    skin_type: ["Sensitive", "Oily", "Combination", "Normal"],
    rating: 4.8,
    review_count: 12450,
    is_bestseller: true,
  },
  {
    slug: "anua-niacinamide-10-serum",
    brand: "Anua",
    name_en: "Niacinamide 10% + TXA 4% Serum",
    name_uz: "Niacinamide 10% + TXA 4% serum",
    name_ru: "Сыворотка Niacinamide 10% + TXA 4%",
    name_ko: "나이아신아마이드 10% + TXA 4% 세럼",
    description_en: "Powerful brightening serum combining 10% Niacinamide and 4% Tranexamic Acid. Targets dark spots, uneven tone, and excess sebum without irritation.",
    description_uz: "10% Niacinamide va 4% Tranexamic Acid bilan kuchli yorituvchi serum. Qorong'u dog'lar, notekis ton va ortiqcha sebumga qarshi.",
    description_ru: "Мощная осветляющая сыворотка с 10% ниацинамида и 4% транексамовой кислоты. Борется с пигментацией и жирным блеском.",
    category_slug: "serums",
    price_usd: 24,
    compare_at_price_usd: 30,
    sku: "ANUA-SER-002",
    stock: 72,
    ingredients: "Niacinamide 10%, Tranexamic Acid 4%, Arbutin, Centella Asiatica",
    benefits: "Brightens, fades dark spots, controls oil, evens skin tone.",
    skin_type: ["Oily", "Combination", "Normal", "Sensitive"],
    rating: 4.7,
    review_count: 8930,
    is_bestseller: true,
  },
  {
    slug: "anua-heartleaf-cream",
    brand: "Anua",
    name_en: "Heartleaf 70% Intense Calming Cream",
    name_uz: "Heartleaf 70% intensiv tinchlantiruvchi krem",
    name_ru: "Heartleaf 70% интенсивный успокаивающий крем",
    name_ko: "하트립 70% 인텐스 카밍 크림",
    description_en: "Rich yet non-greasy cream with 70% Heartleaf extract. Deeply soothes, repairs the moisture barrier, and leaves skin soft and calm.",
    description_uz: "70% Heartleaf ekstrakti bilan boy, lekin yog'siz krem. Chuqur tinchlantiradi va namlik to'sig'ini tiklaydi.",
    description_ru: "Насыщенный, но не жирный крем с 70% экстракта Хартлиф. Глубоко успокаивает и восстанавливает барьер.",
    category_slug: "moisturizers",
    price_usd: 26,
    compare_at_price_usd: 32,
    sku: "ANUA-CRM-003",
    stock: 48,
    ingredients: "Houttuynia Cordata Extract 70%, Ceramide NP, Panthenol, Squalane",
    benefits: "Calms redness, repairs barrier, long-lasting hydration.",
    skin_type: ["Sensitive", "Dry", "Normal"],
    rating: 4.6,
    review_count: 4120,
    is_bestseller: true,
  },
  {
    slug: "anua-soft-sunscreen",
    brand: "Anua",
    name_en: "Heartleaf Soft Sunscreen SPF50+ PA++++",
    name_uz: "Heartleaf yumshoq quyoshdan himoya SPF50+",
    name_ru: "Heartleaf мягкий санскрин SPF50+ PA++++",
    name_ko: "하트립 소프트 선크림 SPF50+",
    description_en: "Lightweight chemical sunscreen with Heartleaf extract. No white cast, invisible finish, perfect under makeup. Broad spectrum SPF50+ PA++++.",
    description_uz: "Heartleaf ekstrakti bilan engil kimyoviy quyoshdan himoya. Oq iz qoldirmaydi, makiyaj ostida mukammal.",
    description_ru: "Лёгкий химический санскрин с экстрактом Хартлиф. Без белых следов, идеально под макияж.",
    category_slug: "sunscreens",
    price_usd: 20,
    compare_at_price_usd: 25,
    sku: "ANUA-SPF-004",
    stock: 95,
    ingredients: "Houttuynia Cordata Extract, Uvinul A Plus, Tinosorb S, Niacinamide",
    benefits: "SPF50+ PA++++, no white cast, calming, makeup-friendly.",
    skin_type: ["All", "Sensitive", "Oily", "Dry"],
    rating: 4.7,
    review_count: 6780,
    is_bestseller: true,
  },

  // ========== COSRX ==========
  {
    slug: "cosrx-advanced-snail-96",
    brand: "COSRX",
    name_en: "Advanced Snail 96 Mucin Power Essence",
    name_uz: "Advanced Snail 96 Mucin Power Essence",
    name_ru: "Advanced Snail 96 Mucin Power Essence",
    name_ko: "어드밴스드 스네일 96 뮤신 파워 에센스",
    description_en: "The iconic 96% snail secretion filtrate essence. Repairs, hydrates, and improves skin texture for that glass-skin effect.",
    description_uz: "Mashhur 96% salyangoz sekreti filtrati. Tiklaydi, namlaydi va teri teksturasini yaxshilaydi.",
    description_ru: "Культовая эссенция с 96% фильтрата секреции улитки. Восстанавливает, увлажняет и улучшает текстуру.",
    category_slug: "serums",
    price_usd: 25,
    compare_at_price_usd: 29,
    sku: "COSRX-ESS-001",
    stock: 110,
    ingredients: "Snail Secretion Filtrate 96%, Sodium Hyaluronate, Betaine",
    benefits: "Repairs, hydrates, softens, glass-skin finish.",
    skin_type: ["Dry", "Normal", "Combination", "Sensitive"],
    rating: 4.9,
    review_count: 45200,
    is_bestseller: true,
  },
  {
    slug: "cosrx-low-ph-cleanser",
    brand: "COSRX",
    name_en: "Low pH Good Morning Gel Cleanser",
    name_uz: "Low pH Good Morning gel tozalagich",
    name_ru: "Low pH Good Morning гель-очиститель",
    name_ko: "로우 pH 굿모닝 젤 클렌저",
    description_en: "Gentle low-pH gel cleanser with BHA. Removes impurities without stripping the skin barrier. Ideal for morning use.",
    description_uz: "BHA bilan yumshoq past pH gel tozalagich. Teri to'sig'ini buzmasdan tozalaydi.",
    description_ru: "Мягкий гель с низким pH и BHA. Очищает, не нарушая барьер.",
    category_slug: "cleansers",
    price_usd: 14,
    compare_at_price_usd: null,
    sku: "COSRX-CLN-002",
    stock: 140,
    ingredients: "Tea Tree Leaf Water, Betaine Salicylate (BHA), Allantoin",
    benefits: "Gentle cleanse, controls oil, maintains pH balance.",
    skin_type: ["Oily", "Combination", "Sensitive"],
    rating: 4.6,
    review_count: 28900,
    is_bestseller: true,
  },
  {
    slug: "cosrx-aloe-sunscreen",
    brand: "COSRX",
    name_en: "Aloe Soothing Sun Cream SPF50+ PA+++",
    name_uz: "Aloe tinchlantiruvchi quyosh kremi SPF50+",
    name_ru: "Aloe успокаивающий солнцезащитный крем SPF50+",
    name_ko: "알로에 수딩 선크림 SPF50+",
    description_en: "Lightweight aloe-based sunscreen. Cooling, non-greasy, and suitable for sensitive skin. SPF50+ PA+++.",
    description_uz: "Aloe asosidagi engil quyoshdan himoya. Sovutadi, yog'siz, sezgir teri uchun mos.",
    description_ru: "Лёгкий санскрин на основе алоэ. Охлаждает, не жирный, подходит для чувствительной кожи.",
    category_slug: "sunscreens",
    price_usd: 18,
    compare_at_price_usd: 22,
    sku: "COSRX-SPF-003",
    stock: 65,
    ingredients: "Aloe Vera Leaf Extract, Zinc Oxide, Titanium Dioxide",
    benefits: "SPF50+, soothing, lightweight, no white cast.",
    skin_type: ["Sensitive", "Dry", "Normal"],
    rating: 4.5,
    review_count: 9200,
    is_bestseller: false,
  },

  // ========== BEAUTY OF JOSEON ==========
  {
    slug: "boj-glow-serum",
    brand: "Beauty of Joseon",
    name_en: "Glow Deep Serum Propolis + Niacinamide",
    name_uz: "Glow Deep Serum Propolis + Niacinamide",
    name_ru: "Glow Deep Serum Propolis + Niacinamide",
    name_ko: "글로우 딥 세럼 프로폴리스 + 나이아신아마이드",
    description_en: "Honey + propolis powered serum that brightens, hydrates, and strengthens the skin barrier. A K-beauty staple.",
    description_uz: "Asal va propolis bilan boyitilgan serum. Yorituvchi, namlovchi va to'siqni mustahkamlaydi.",
    description_ru: "Сыворотка на основе мёда и прополиса. Осветляет, увлажняет и укрепляет барьер.",
    category_slug: "serums",
    price_usd: 17,
    compare_at_price_usd: 21,
    sku: "BOJ-SER-001",
    stock: 90,
    ingredients: "Propolis Extract 60%, Niacinamide 2%, Honey Extract",
    benefits: "Brightens, hydrates, strengthens barrier, glow.",
    skin_type: ["Dry", "Normal", "Combination", "Sensitive"],
    rating: 4.8,
    review_count: 18700,
    is_bestseller: true,
  },
  {
    slug: "boj-relief-sun",
    brand: "Beauty of Joseon",
    name_en: "Relief Sun: Rice + Probiotics SPF50+ PA++++",
    name_uz: "Relief Sun: Guruch + Probiotiklar SPF50+",
    name_ru: "Relief Sun: Рис + Пробиотики SPF50+",
    name_ko: "릴리프 선: 라이스 + 프로바이오틱스 SPF50+",
    description_en: "The internet's favorite Korean sunscreen. Rice extract + probiotics, invisible finish, zero white cast. SPF50+ PA++++.",
    description_uz: "Internetning sevimli koreys quyoshdan himoyasi. Guruch ekstrakti + probiotiklar, oq izsiz.",
    description_ru: "Любимый корейский санскрин интернета. Экстракт риса + пробиотики, без белых следов.",
    category_slug: "sunscreens",
    price_usd: 16,
    compare_at_price_usd: 19,
    sku: "BOJ-SPF-002",
    stock: 150,
    ingredients: "Oryza Sativa (Rice) Extract, Bifida Ferment Lysate, Uvinul A Plus",
    benefits: "SPF50+ PA++++, no white cast, hydrating, makeup base.",
    skin_type: ["All"],
    rating: 4.9,
    review_count: 52300,
    is_bestseller: true,
  },
  {
    slug: "boj-dynasty-cream",
    brand: "Beauty of Joseon",
    name_en: "Dynasty Cream",
    name_uz: "Dynasty krem",
    name_ru: "Dynasty крем",
    name_ko: "다이너스티 크림",
    description_en: "Rich anti-aging cream inspired by traditional Korean herbal medicine. Ginseng + rice bran for firmness and glow.",
    description_uz: "An'anaviy koreys o'simlik tibbiyotidan ilhomlangan boy qarishga qarshi krem.",
    description_ru: "Насыщенный антивозрастной крем по мотивам традиционной корейской медицины.",
    category_slug: "moisturizers",
    price_usd: 22,
    compare_at_price_usd: 27,
    sku: "BOJ-CRM-003",
    stock: 55,
    ingredients: "Ginseng Root Extract, Rice Bran Oil, Niacinamide, Squalane",
    benefits: "Firms, brightens, deeply nourishes, anti-aging.",
    skin_type: ["Dry", "Normal", "Mature"],
    rating: 4.7,
    review_count: 11400,
    is_bestseller: false,
  },

  // ========== ISNTREE ==========
  {
    slug: "isntree-hyaluronic-watery-sun",
    brand: "Isntree",
    name_en: "Hyaluronic Acid Watery Sun Gel SPF50+ PA++++",
    name_uz: "Gialuron kislotali suvli quyosh geli SPF50+",
    name_ru: "Гиалуроновый водянистый солнцезащитный гель SPF50+",
    name_ko: "히알루론산 워터리 선젤 SPF50+",
    description_en: "Ultra-light watery sun gel packed with hyaluronic acid. Fresh, non-sticky, perfect for oily and combination skin.",
    description_uz: "Gialuron kislotasi bilan to'ldirilgan ultra-engil suvli quyosh geli. Yangi, yopishqoq emas.",
    description_ru: "Ультралёгкий водянистый гель с гиалуроновой кислотой. Свежий, не липкий.",
    category_slug: "sunscreens",
    price_usd: 19,
    compare_at_price_usd: 24,
    sku: "ISN-SPF-001",
    stock: 70,
    ingredients: "Hyaluronic Acid, Panthenol, Centella Asiatica, Chemical UV filters",
    benefits: "SPF50+ PA++++, watery texture, hydrating, no white cast.",
    skin_type: ["Oily", "Combination", "Normal"],
    rating: 4.6,
    review_count: 7800,
    is_bestseller: false,
  },
  {
    slug: "isntree-green-tea-fresh-toner",
    brand: "Isntree",
    name_en: "Green Tea Fresh Toner",
    name_uz: "Yashil choy yangi toner",
    name_ru: "Тонер с зелёным чаем",
    name_ko: "그린티 프레시 토너",
    description_en: "Refreshing toner with green tea extract. Controls sebum, soothes, and balances skin after cleansing.",
    description_uz: "Yashil choy ekstrakti bilan yangilovchi toner. Sebumni nazorat qiladi va tinchlantiradi.",
    description_ru: "Освежающий тонер с экстрактом зелёного чая. Контролирует себум и успокаивает.",
    category_slug: "serums",
    price_usd: 18,
    compare_at_price_usd: null,
    sku: "ISN-TON-002",
    stock: 60,
    ingredients: "Camellia Sinensis Leaf Extract, Centella Asiatica, Panthenol",
    benefits: "Sebum control, soothes, refreshes, balances pH.",
    skin_type: ["Oily", "Combination", "Sensitive"],
    rating: 4.5,
    review_count: 5400,
    is_bestseller: false,
  },

  // ========== AUVRENZA (house brand) ==========
  {
    slug: "centella-repair-serum",
    brand: "AUVRENZA",
    name_en: "Centella Repair Serum",
    name_uz: "Centella tiklovchi serum",
    name_ru: "Centella восстанавливающая сыворотка",
    name_ko: "센텔라 리페어 세럼",
    description_en: "A calming, barrier-repairing serum built around Centella Asiatica extract — soothes redness and strengthens sensitive skin over time.",
    description_uz: "Centella Asiatica ekstrakti atrofida qurilgan tinchlantiruvchi, to'siqni tiklovchi serum.",
    description_ru: "Успокаивающая сыворотка на основе экстракта центеллы азиатской — снимает покраснение и укрепляет барьер.",
    category_slug: "serums",
    price_usd: 46,
    compare_at_price_usd: 58,
    sku: "AV-SER-001",
    stock: 42,
    ingredients: "Centella Asiatica Extract, Panthenol, Niacinamide, Hyaluronic Acid, Madecassoside",
    benefits: "Reduces redness, strengthens skin barrier, calms irritation, deeply hydrates.",
    skin_type: ["Sensitive", "Dry", "Combination"],
    rating: 4.8,
    review_count: 412,
    is_bestseller: true,
  },
  {
    slug: "ginseng-renewal-cream",
    brand: "AUVRENZA",
    name_en: "Ginseng Renewal Cream",
    name_uz: "Jenshen yangilovchi krem",
    name_ru: "Крем с женьшенем для обновления",
    name_ko: "인삼 리뉴얼 크림",
    description_en: "A rich, anti-aging moisturizer built on Korean red ginseng root extract to firm and renew mature skin.",
    description_uz: "Koreys qizil jenshen ildizi ekstrakti asosidagi boy qarishga qarshi namlagich.",
    description_ru: "Насыщенный антивозрастной крем на основе экстракта корня красного женьшеня.",
    category_slug: "moisturizers",
    price_usd: 58,
    compare_at_price_usd: 72,
    sku: "AV-CRM-003",
    stock: 18,
    ingredients: "Korean Red Ginseng Root Extract, Ceramides, Peptides, Squalane",
    benefits: "Firms, renews, deeply nourishes, reduces the look of fine lines.",
    skin_type: ["Dry", "Normal"],
    rating: 4.6,
    review_count: 190,
    is_bestseller: true,
  },
  {
    slug: "relief-sun-spf50",
    brand: "AUVRENZA",
    name_en: "Relief Sun SPF50+",
    name_uz: "Relief Sun SPF50+",
    name_ru: "Relief Sun SPF50+",
    name_ko: "릴리프 선 SPF50+",
    description_en: "A weightless, no-white-cast mineral-hybrid sunscreen for daily protection.",
    description_uz: "Kundalik himoya uchun og'irsiz, oq izsiz mineral-gibrid quyoshdan himoya.",
    description_ru: "Невесомый минерально-гибридный санскрин без белых следов для ежедневной защиты.",
    category_slug: "sunscreens",
    price_usd: 28,
    compare_at_price_usd: 34,
    sku: "AV-SPF-006",
    stock: 38,
    ingredients: "Zinc Oxide, Niacinamide, Centella Asiatica Extract",
    benefits: "Broad-spectrum SPF50+, no white cast, lightweight daily wear.",
    skin_type: ["Normal", "Oily", "Sensitive"],
    rating: 4.7,
    review_count: 322,
    is_bestseller: false,
  },
  {
    slug: "low-ph-gel-cleanser",
    brand: "AUVRENZA",
    name_en: "Low pH Gel Cleanser",
    name_uz: "Past pH gel tozalagich",
    name_ru: "Гель-очиститель с низким pH",
    name_ko: "로우 pH 젤 클렌저",
    description_en: "A gentle, low-pH gel cleanser that removes impurities without disrupting the skin barrier.",
    description_uz: "Teri to'sig'ini buzmasdan iflosliklarni olib tashlaydigan yumshoq past pH gel tozalagich.",
    description_ru: "Мягкий гель с низким pH, который удаляет загрязнения, не нарушая барьер.",
    category_slug: "cleansers",
    price_usd: 24,
    compare_at_price_usd: null,
    sku: "AV-CLN-005",
    stock: 60,
    ingredients: "Tea Tree Leaf Water, Betaine Salicylate, Panthenol",
    benefits: "Cleanses gently, maintains barrier, controls excess oil.",
    skin_type: ["Oily", "Combination", "Sensitive"],
    rating: 4.5,
    review_count: 145,
    is_bestseller: false,
  },
];

async function seed() {
  console.log("Seeding categories…");
  const categoryMap: Record<string, string> = {};
  for (const cat of categories) {
    const { slug, ...rest } = cat;
    const { data, error } = await supabase.from("categories").upsert({ slug, ...rest }, { onConflict: "slug" }).select("id, slug").single();
    if (error) console.error(`  ✗ ${slug}:`, error.message);
    else { categoryMap[slug] = data.id; console.log(`  ✓ ${slug}`); }
  }

  console.log("Seeding products…");
  for (const p of products) {
    const { category_slug, ...rest } = p;
    const { error } = await supabase
      .from("products")
      .upsert({ ...rest, category_id: categoryMap[category_slug] ?? null, is_active: true }, { onConflict: "slug" });
    if (error) console.error(`  ✗ ${p.slug}:`, error.message);
    else console.log(`  ✓ ${p.slug} (${p.brand})`);
  }

  console.log("Seeding a starter coupon…");
  await supabase.from("coupons").upsert(
    { code: "WELCOME10", type: "percent", value: 10, active: true },
    { onConflict: "code" }
  );

  console.log("Done. Seeded", products.length, "products across brands: Anua, COSRX, Beauty of Joseon, Isntree, AUVRENZA.");
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
